spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: thibaut.lenertz@gmail.com
    password: 9b2zSrEn3Y36Ac
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  datasource:
    url: jdbc:postgresql://localhost:5432/belgianslotclub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    web:
      resources:
        static-locations: classpath:/static/, file:./images/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
server:
  port: 8080



